// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pfe.Models;

namespace pfe.Migrations
{
    [DbContext(typeof(GestContext))]
    partial class PayeurContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("pfe.Models.Compte", b =>
                {
                    b.Property<int>("CompteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CO")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CR")
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("CompteDB")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DB")
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Lib")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OuvertCR")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OuvertDB")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TypeCompte")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("CompteId");

                    b.ToTable("Comptes");
                });

            modelBuilder.Entity("pfe.Models.DepBancaire", b =>
                {
                    b.Property<int>("DepBanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CO")
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Libelle")
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("MVT")
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Montant")
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("NCH")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Tiers")
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("DepBanId");

                    b.ToTable("DepBancaires");
                });

            modelBuilder.Entity("pfe.Models.DepCaisse", b =>
                {
                    b.Property<int>("DepBanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CO")
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Libelle")
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("MVT")
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Montant")
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Recu")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Tiers")
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("DepBanId");

                    b.ToTable("DepCaisses");
                });

            modelBuilder.Entity("pfe.Models.Payeur", b =>
                {
                    b.Property<int>("PayeurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CardNumber")
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("CardOwnerName")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("PayeurId");

                    b.ToTable("Payeurs");
                });

            modelBuilder.Entity("pfe.Models.RecBancaire", b =>
                {
                    b.Property<int>("DepBanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CO")
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Libelle")
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("MVT")
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Montant")
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("NCH")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Tiers")
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("DepBanId");

                    b.ToTable("RecBancaires");
                });

            modelBuilder.Entity("pfe.Models.RecCaisse", b =>
                {
                    b.Property<int>("DepBanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CO")
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Libelle")
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("MVT")
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Montant")
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Recu")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Tiers")
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("DepBanId");

                    b.ToTable("RecCaisses");
                });
#pragma warning restore 612, 618
        }
    }
}
